/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2021-07-13-f531a1a"
#endif /* AVUTIL_FFVERSION_H */
